### ISSUE TITLE
New MT32Emu framework misses ReportHandler

### ISSUE THREAD

**Issue by Kentzo** [alunbestor/Boxer#16]
New version of MT32Emu framework introduced in 67cd4ab9ee24708ca88ae9b7b9a4820df4b419bf misses ReportHandler. App fails to launch with the following error:

> dyld: Symbol not found: __ZTIN7MT32Emu13ReportHandlerE
>   Referenced from: …/Boxer.app/Contents/MacOS/Boxer
>   Expected in …/Boxer.app/Contents/MacOS/../Frameworks/MT32Emu.framework/Versions/A/MT32Emu
>  in …/Boxer.app/Contents/MacOS/Boxer
